apiVersion: v1
kind: Secret
metadata:
  name: temporal-db
  namespace: temporal
  labels:
    app.kubernetes.io/part-of: temporal-kind
type: kubernetes.io/basic-auth
stringData:
  username: temporal
  password: temporal
