apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: temporal-frontend
  namespace: temporal
  labels:
    app.kubernetes.io/part-of: temporal-kind
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: temporal-local
      namespace: kgateway-system
      sectionName: temporal-frontend
  hostnames:
    - temporal.localhost
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: temporal-frontend
          port: 7233
          weight: 1
